/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.renato.gameoflife;

import java.awt.GridLayout;

/**
 *
 * @author renat
 */
public class MainWindow extends javax.swing.JFrame {

    Game game;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }
    
    public MainWindow(Game game){
        this();
        this.game = game;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gridPanel = new javax.swing.JPanel();
        nexGenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        gridPanel.setBackground(new java.awt.Color(0, 0, 0));
        gridPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gridPanel.setMinimumSize(new java.awt.Dimension(50, 50));
        gridPanel.setLayout(new java.awt.GridLayout(10, 10, 1, 1));
        getContentPane().add(gridPanel, java.awt.BorderLayout.CENTER);

        nexGenButton.setLabel("Próxima geração");
        nexGenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nexGenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nexGenButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nexGenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nexGenButtonActionPerformed
        game.calculateNextGeneration();
    }//GEN-LAST:event_nexGenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    //carrega botoes no grid
    public void populateGrid(){
        gridPanel.setLayout(new GridLayout(game.gridSize, game.gridSize));
        for (int i = 0; i < game.gridSize; i++){
            for (int j = 0; j < game.gridSize; j++){          
                gridPanel.add(game.grid[i][j].cellButton);
            }
        }
        gridPanel.setSize(10*game.gridSize, 10*game.gridSize);
        
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gridPanel;
    private javax.swing.JButton nexGenButton;
    // End of variables declaration//GEN-END:variables
}
